# Featuring Engineering Using Scikit-Learn: Column Transformer and Pipeline

### Do You Want to Build a Snowman?

Let's prep some data for a model to predict the height of snowman.

<img src = "./assets/olaf.jpeg">

#### Load Packages

In [1]:
# data analysis stack
import numpy as np
import pandas as pd

# data visualization stack
import matplotlib.pyplot as plt

%matplotlib inline
import seaborn as sns

sns.set_style("whitegrid")

# machine-learning stack
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import (
    OneHotEncoder,
    StandardScaler,
    RobustScaler,
    MinMaxScaler,
    KBinsDiscretizer,
    PolynomialFeatures,
)

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# miscellaneous
import warnings

warnings.filterwarnings("ignore")

#### Load Data

In [2]:
data = {
    "temp": [-3, 5, 0, 7, 3, -1, 1, None, -6, 3, 0, -1, None, -2],
    "lunch": [
        "soup",
        "sandwich",
        "soup",
        "burger",
        "sandwich",
        "soup",
        "cereal",
        "salad",
        "sandwich",
        "burger",
        "soup",
        "cereal",
        "burger",
        "soup",
    ],
    "dinner": [
        "pizza",
        "pizza",
        "noodles",
        None,
        "fishsticks",
        "pizza",
        None,
        "fishsticks",
        "noodles",
        "pizza",
        None,
        "pizza",
        "fishsticks",
        "pizza",
    ],
    "precipitation": [
        "yes",
        "no",
        "yes",
        "yes",
        "yes",
        "yes",
        "no",
        "yes",
        "yes",
        "no",
        "yes",
        "yes",
        "yes",
        "no",
    ],
    "height_snowman_cm": [100, 0, 75, 0, 20, 25, 0, 35, 170, 0, 85, 85, 45, 0],
}

df_train = pd.DataFrame(data=data)
df_train

    temp     lunch      dinner precipitation  height_snowman_cm
0   -3.0      soup       pizza           yes                100
1    5.0  sandwich       pizza            no                  0
2    0.0      soup     noodles           yes                 75
3    7.0    burger         NaN           yes                  0
4    3.0  sandwich  fishsticks           yes                 20
5   -1.0      soup       pizza           yes                 25
6    1.0    cereal         NaN            no                  0
7    NaN     salad  fishsticks           yes                 35
8   -6.0  sandwich     noodles           yes                170
9    3.0    burger       pizza            no                  0
10   0.0      soup         NaN           yes                 85
11  -1.0    cereal       pizza           yes                 85
12   NaN    burger  fishsticks           yes                 45
13  -2.0      soup       pizza            no                  0

#### Exercise
Transform the data above using scikit-learn tools in combination with `ColumnTransformer()` and `Pipeline()` in a way that is suitable for modeling
+ **Separate the DataFrame `df_train` into `X_train` and `y_train`** 
   +  Our target variable is `height_snowman_cm`
+ **Preprocess `X_train`**:
  + Identify which variables are **binary**, **categorical** and  **numeric**
  + Check which variables have **missing values**
    + **Impute missing values** as needed using appropriate strategies
  + Determine if categorical variables have **non-numeric values**
    + **Encode categorical variables** using techniques such as one-hot encoding
  + Determine if numeric variables are on different scales
    + **Scale numeric variables**
+ **Create `X_train_fe`**:
    + Once the preprocessing steps are completed, compile the transformed columns into a new DataFrame called `X_train_fe`.

#### 1. Separate `df_train` into `X_train` and `y_train`

In [3]:
target = "height_snowman_cm"

X_train = df_train.drop(columns=target)
y_train = df_train[target]
X_train

    temp     lunch      dinner precipitation
0   -3.0      soup       pizza           yes
1    5.0  sandwich       pizza            no
2    0.0      soup     noodles           yes
3    7.0    burger         NaN           yes
4    3.0  sandwich  fishsticks           yes
5   -1.0      soup       pizza           yes
6    1.0    cereal         NaN            no
7    NaN     salad  fishsticks           yes
8   -6.0  sandwich     noodles           yes
9    3.0    burger       pizza            no
10   0.0      soup         NaN           yes
11  -1.0    cereal       pizza           yes
12   NaN    burger  fishsticks           yes
13  -2.0      soup       pizza            no

#### 2. Preprocess `X_train`

`temp` is the only numeric feature (with missing values to impute and a scale to normalize). `lunch`, `dinner` and `precipitation` are categorical (with `dinner` also missing values), so they need imputing and one-hot encoding. We wire each column type into its own `Pipeline`, then combine both pipelines with a `ColumnTransformer`.

In [4]:
numeric_features = ["temp"]
categorical_features = ["lunch", "dinner", "precipitation"]

In [5]:
numeric_pipeline = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="mean")),
        ("scaler", StandardScaler()),
    ]
)
numeric_pipeline

Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler())])

In [6]:
categorical_pipeline = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("ohe", OneHotEncoder(sparse_output=False, drop="if_binary")),
    ]
)
categorical_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('ohe', OneHotEncoder(drop='if_binary', sparse_output=False))])

Combine both column-wise pipelines with `ColumnTransformer`

In [7]:
preprocessor = ColumnTransformer(
    transformers=[
        ("numeric", numeric_pipeline, numeric_features),
        ("categorical", categorical_pipeline, categorical_features),
    ]
).set_output(transform="pandas")
preprocessor

ColumnTransformer(transformers=[('numeric',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['temp']),
                                ('categorical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('ohe',
                                                  OneHotEncoder(drop='if_binary',
                                                                sparse_output=False))]),
                                 ['lunch', 'dinner', 'precipitation'])])

In [8]:
preprocessor.fit(X_train)

ColumnTransformer(transformers=[('numeric',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['temp']),
                                ('categorical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('ohe',
                                                  OneHotEncoder(drop='if_binary',
                                                                sparse_output=False))]),
                                 ['lunch', 'dinner', 'precipitation'])])

#### 3. Create `X_train_fe`

In [9]:
X_train_fe = preprocessor.transform(X_train)
X_train_fe

,numeric__temp,categorical__lunch_burger,categorical__lunch_cereal,categorical__lunch_salad,categorical__lunch_sandwich,categorical__lunch_soup,categorical__dinner_fishsticks,categorical__dinner_noodles,categorical__dinner_pizza,categorical__precipitation_yes
0,-1.102865,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
1,1.417970,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,-0.157552,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
3,2.048179,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
4,0.787761,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
5,-0.472657,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
6,0.157552,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7,0.000000,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
8,-2.048179,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
9,0.787761,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10,-0.157552,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
11,-0.472657,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
12,0.000000,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
13,-0.787761,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0